### ISSUE TITLE
API to get historical data

### ISSUE THREAD

**Issue by mearns** [cainus/codecov.io#20]
It's awesome that I can use a simple API to get the current report, but I'd love to be able to get historical data as well. I don't need full reports from the past, just the coverage, and if possible, the total counts for past commits.

My primary use case is to build a customized graph of the data. Not that the graphs provided on the branch.svg endpoint aren't nice, but they aren't =). More importantly, I want to be able to combine this data with other data I'm collecting out of band, like who is making the commits, how busy development is, etc.

**Comment by stevepeak** [comment]
Hey @mearns https://codecov.io/api would be the first place to start. We have a couple support tickets related to metrics on https://github.com/codecov/support/issues that you are welcome to chat on as well.

Thank you!
