### ISSUE TITLE
Passing file as filepath

### ISSUE THREAD

**Issue by magestican** [cainus/codecov.io#24]
Could you support passing the filepath and avoid using FIND command in order to find my lcov.info ?

something like codecov --token=123123 --filepath=coverage/lcov.info

Would be greatly appreciated

**Comment by stevepeak** [comment]
Hey @magestican we are going to be transitioning to another package soon: https://github.com/codecov/codecov-node

```
npm install codecov
codecov --token=123123 --file=coverage/lcov.info
```

Thank you!
