### ISSUE TITLE
Partial line coverage false fail.

### ISSUE THREAD

**Issue by jdalton** [cainus/codecov.io#27]
I know partial line coverage is still a WIP but I figured I'd highlight a false positive.
It's the only one I've hit so far.

See [the report](https://codecov.io/github/lodash-archive/lodash-node/modern/function/debounce.js?ref=673100261dc52c14a3259718963fa4193ab1dbd1). The issue is with:
```js
if ((timeoutId && trailingCall) || (maxTimeoutId && trailing)) {
```
both conditions are hit via the unit tests.

**Comment by hbetts** [comment]
@jdalton I believe the more appropriate place to file this issue would be on the CodeCov support site: https://github.com/codecov/support

The `codecov.io` tool does nothing more than upload the contents of the piped file.
