### ISSUE TITLE
Publish 0.1.7 to npm

### ISSUE THREAD

**Issue by jvincilione** [cainus/codecov.io#32]

**Comment by jvincilione** [comment]
@cainus Any idea when you can do this?

**Comment by stevepeak** [comment]
@jvincilione I recommend switching to https://github.com/codecov/codecov-node
It's more actively developed. 👍

**Comment by jvincilione** [comment]
@stevepeak This isn't for me. It's a dep of a package I'm using. The update has already been done on this package, it's just not published. Also, I believe the package switched, but there was a bug with codecov-node, so they switched back. (I gathered that from the issues)

**Comment by stevepeak** [comment]
Ok, I'll publish this package to npm now. Thanks

**Comment by stevepeak** [comment]
Released 👍

**Comment by evanlucas** [comment]
This is breaking builds using node-tap. See https://github.com/cainus/codecov.io/issues/33

**Comment by jvincilione** [comment]
Thanks @stevepeak

**Comment by fruchtose** [comment]
Also seeing broken builds using this release.

**Comment by fruchtose** [comment]
@stevepeak please fix the broken release.
