### ISSUE TITLE
code coverage shows wrong

### ISSUE THREAD

**Issue by gorilla001** [cainus/codecov.io#36]
when travis shows total coverage 74%, codecov.io shows only 66.63%.

**Comment by stevepeak** [comment]
@pwzgorilla can you ping me a link to Codecov expressing this? I'm sure I can find an explanation to this. Thank you!

**Comment by gorilla001** [comment]
@stevepeak https://codecov.io/gh/Dataman-Cloud/swan https://travis-ci.org/Dataman-Cloud/swan/builds/173864741

**Comment by stevepeak** [comment]
@pwzgorilla Go reports go though a filter to remove empty lines and ending brackets. This is causing the change in coverage. More here: http://docs.codecov.io/docs/fixing-reports#section-go

You can disable this in the following manner:

```
bash <(curl -s https://codecov.io/bash) -X fix
```

Thanks!

**Comment by gorilla001** [comment]
@stevepeak seems no use. https://travis-ci.org/Dataman-Cloud/swan https://codecov.io/gh/Dataman-Cloud/swan

**Comment by gorilla001** [comment]
@stevepeak very appreciate, but actually i  have done this in another PR(https://github.com/Dataman-Cloud/swan/pull/13), and still no effect, travis shows 70%+, but codecov shows 60%+.

Very appreciate!
