### ISSUE TITLE
Unknown service could not get configuration

### ISSUE THREAD

**Issue by ilanbiala** [cainus/codecov.io#7]
/Users/Ilan/Development/hths-lunch/node_modules/codecov.io/lib/getConfiguration.js:19
    throw new Error("unknown service.  could not get configuration");
          ^
Error: unknown service.  could not get configuration
    at module.exports (project/node_modules/codecov.io/lib/getConfiguration.js:19:11)
    at sendToCodecov (project/node_modules/codecov.io/lib/sendToCodeCov.io.js:12:23)
    at Socket.<anonymous> (project/node_modules/codecov.io/bin/codecov.io.js:14:5)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

passing in 'mocha-lcov-reporter' to gulp-mocha.

Would also be nice to have better errors.

**Comment by kytwb** [comment]
:+1:

**Comment by stevepeak** [comment]
The only required variable are `branch` and `commit` the rest are optional. We must exclude the other arguments when uploading locally.

Working on this via #8

**Comment by stevepeak** [comment]
@ilanbiala @kytwb I will be deploying a new node uploader shortly. It will enhance Codecov to show off partial line coverage. Let me know if you are interested in helping out testing it. Thanks!

**Comment by ilanbiala** [comment]
@stevepeak sure you can ping me when it's ready for testing.

**Comment by kytwb** [comment]
@stevepeak same :+1:
